#!/bin/bash
#
# Smart Clock: Power on/off
# Powers LED matrix on and off to save energy
#
# For coding style, tries to follow https://google.github.io/styleguide/shellguide.html
# For License information, see included LICENSE
#


SCRIPT_PATH="$(dirname "$0")"
# shellcheck source=/dev/null
source "$SCRIPT_PATH/config.sh"
# shellcheck source=/dev/null
source "$SCRIPT_PATH/smartclock.sh"

case "$1" in
on)
  smartclock::power "power=true"
  exit
  ;;

off)
  smartclock::power "power=false"
  exit
  ;;

*)
  echo "Usage: ./$0 on|off"
  ;;

esac
