#!/bin/bash
#
# Smart Clock: Power on/off
# Toggles LED matrix on and off to save energy
#
# For coding style, tries to follow https://google.github.io/styleguide/shellguide.html
# For License information, see included LICENSE
#
# TODO(r0max): allow power state to be passed in, overriding toggle
#

# shellcheck disable=SC1091
source $(dirname "$0")/config.sh
source $(dirname "$0")/smartclock.sh

function sc-on() {
  touch ${TOGGLE}
  smartclock::power "power=true"
}

function sc-off() {
  if [ -f "${TOGGLE}" ]; then
    rm ${TOGGLE}
  fi
  smartclock::power "power=false"
}

if [ ! -e ${TOGGLE} ]; then
  sc-on
else
  sc-off
fi
